// User & roles — sourced from Prisma so there is a single source of truth
export { UserRole, AppStatus, SyncRequestStatus, NotificationEventType, OrgStatus, AuthMode, OrgMemberRole } from "@prisma/client";

// Tokens
export enum TokenType {
  ACCESS = "access",
  REFRESH = "refresh",
}

export const DEFAULT_ACCESS_TOKEN_EXPIRY = "15m";
export const DEFAULT_REFRESH_TOKEN_EXPIRY = "7d";

// Audit actions (auth-centric)
export enum AuditAction {
  USER_REGISTERED = "USER_REGISTERED",
  LOGIN_SUCCESS = "LOGIN_SUCCESS",
  LOGIN_FAILED = "LOGIN_FAILED",
  LOGOUT = "LOGOUT",
  LOGOUT_ALL = "LOGOUT_ALL",
  TOKEN_REFRESHED = "TOKEN_REFRESHED",
  TOKEN_REVOKED = "TOKEN_REVOKED",
  PASSWORD_CHANGED = "PASSWORD_CHANGED",
  PASSWORD_RESET_REQUESTED = "PASSWORD_RESET_REQUESTED",
  PASSWORD_RESET_COMPLETED = "PASSWORD_RESET_COMPLETED",
  EMAIL_VERIFICATION_SENT = "EMAIL_VERIFICATION_SENT",
  EMAIL_VERIFIED = "EMAIL_VERIFIED",
  ACCOUNT_LOCKED = "ACCOUNT_LOCKED",
  ACCOUNT_UNLOCKED = "ACCOUNT_UNLOCKED",
  ACCOUNT_DEACTIVATED = "ACCOUNT_DEACTIVATED",
  ACCOUNT_DELETED = "ACCOUNT_DELETED",
  PROFILE_UPDATED = "PROFILE_UPDATED",
  USER_UPDATED = "USER_UPDATED",
  ADMIN_FORCE_ACTIVATED = "ADMIN_FORCE_ACTIVATED",
  // App / RBAC
  APP_CREATED = "APP_CREATED",
  APP_UPDATED = "APP_UPDATED",
  APP_SUSPENDED = "APP_SUSPENDED",
  APP_REACTIVATED = "APP_REACTIVATED",
  APP_SECRET_REGENERATED = "APP_SECRET_REGENERATED",
  FEATURE_ADDED = "FEATURE_ADDED",
  FEATURE_UPDATED = "FEATURE_UPDATED",
  FEATURE_REMOVED = "FEATURE_REMOVED",
  SYNC_REQUEST_APPROVED = "SYNC_REQUEST_APPROVED",
  SYNC_REQUEST_REJECTED = "SYNC_REQUEST_REJECTED",
  ROLE_CREATED = "ROLE_CREATED",
  ROLE_UPDATED = "ROLE_UPDATED",
  ROLE_DELETED = "ROLE_DELETED",
  ROLE_FEATURES_SET = "ROLE_FEATURES_SET",
  USER_APP_ASSIGNED = "USER_APP_ASSIGNED",
  USER_APP_UPDATED = "USER_APP_UPDATED",
  USER_APP_REMOVED = "USER_APP_REMOVED",
  USER_FEATURES_SET = "USER_FEATURES_SET",
  // Organizations
  ORG_CREATED = "ORG_CREATED",
  ORG_UPDATED = "ORG_UPDATED",
  ORG_SUSPENDED = "ORG_SUSPENDED",
  ORG_REACTIVATED = "ORG_REACTIVATED",
  ORG_SECRET_REGENERATED = "ORG_SECRET_REGENERATED",
  ORG_MEMBER_ADDED = "ORG_MEMBER_ADDED",
  ORG_MEMBER_REMOVED = "ORG_MEMBER_REMOVED",
  // Org end-user actions
  ORG_USER_REGISTERED = "ORG_USER_REGISTERED",
  ORG_USER_LOGIN = "ORG_USER_LOGIN",
}

// Password rules
export const PASSWORD_REQUIREMENTS = {
  minLength: 8,
  maxLength: 128,
  requireUppercase: true,
  requireLowercase: true,
  requireNumbers: true,
  requireSpecialChars: true,
  specialChars: "!@#$%^&*()_+-=[]{}|;:,.<>?",
};

export const PASSWORD_REGEX = /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$/;
